# Generated by Django 4.2.16 on 2024-09-22 20:24
import datetime
from django.db import migrations

def create_initial_data(apps, schema_editor):
    # Get your models
    Event = apps.get_model('booking', 'Event')
    Slot = apps.get_model('booking', 'Slot')

    # Create initial data
    event_1 = Event.objects.create(
        name = "Event-1"
        , description = "Test Event 1"
        , date = datetime.date(2024, 10, 1)
    )
    event_2 = Event.objects.create(
        name = "Event-2"
        , description = "Test Event 2"
        , date = datetime.date(2024, 10, 2)
    )
    for h in range(24):
        Slot.objects.create(
                event = event_1
                , start_time = datetime.time(h, 0, 0)
                , end_time = datetime.time(h, 59, 59)
                , capacity = 5
            )
        for m in (0, 15, 30, 45):
            Slot.objects.create(
                event = event_2
                , start_time = datetime.time(h, m, 0)
                , end_time = datetime.time(h, m+14, 59)
                , capacity = 3
            )
        

class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
